import { NewsArticle, MarketContextItem } from '@/types/news';

export const mockNewsArticles: NewsArticle[] = [
  {
    id: 'news-1',
    headline: 'Crude Oil Slides Below $72 as Saudi Output Hikes Offset Middle East Risk',
    source: 'Bloomberg Financial',
    timeAgo: '18m ago',
    timestamp: '14:42 IST',
    category: 'Macro',
    impact: 'High',
    relatedSymbols: ['RELIANCE', 'BPCL', 'ONGC', 'IOC'],
    summary: 'Brent crude dipped 1.7% to $71.85, boosting margin visibility for domestic state-run OMCs and specialty chemical producers while tempering upstream realization expectations.',
  },
  {
    id: 'news-2',
    headline: 'Auto Dispatches Surge Ahead of Navratri Festive Peak; M&M, Tata Motors Hit Multi-Month Highs',
    source: 'Economic Times',
    timeAgo: '42m ago',
    timestamp: '14:18 IST',
    category: 'Sector',
    impact: 'High',
    relatedSymbols: ['TATAMOTORS', 'M&M', 'MARUTI', 'BAJAJ-AUTO'],
    summary: 'Dealership inventory buildup for SUV and premium passenger vehicles indicates double-digit volume growth heading into the festive holiday cycle.',
  },
  {
    id: 'news-3',
    headline: 'HDFC Bank Advances Deposit Mobilization Strategy; Net Interest Margin Stabilizing Around 3.5%',
    source: 'Reuters India',
    timeAgo: '1h 12m ago',
    timestamp: '13:48 IST',
    category: 'Corporate',
    impact: 'Medium',
    relatedSymbols: ['HDFCBANK', 'ICICIBANK', 'KOTAKBANK'],
    summary: 'Branch network expansion in Tier-2/3 centers accelerates retail CASA ratio traction, easing merger transition headwind concerns.',
  },
  {
    id: 'news-4',
    headline: 'RBI Maintains Status Quo on Repo Rate at 6.5%; Stance Neutral Following Moderating Core Inflation',
    source: 'Mint Markets',
    timeAgo: '2h 30m ago',
    timestamp: '12:30 IST',
    category: 'Macro',
    impact: 'High',
    relatedSymbols: ['BANKNIFTY', 'SBIN', 'BAJFINANCE'],
    summary: 'Monetary Policy Committee votes 5-1 to hold key policy benchmark rate steady while emphasizing vigilance on food basket seasonal price pressures.',
  },
  {
    id: 'news-5',
    headline: 'US Tech Spending Environment Shows Early Signs of Budget Thaw; Large Enterprise BFSI Renewals Underway',
    source: 'CNBC-TV18',
    timeAgo: '3h 15m ago',
    timestamp: '11:45 IST',
    category: 'Sector',
    impact: 'Medium',
    relatedSymbols: ['TCS', 'INFY', 'WIPRO', 'HCLTECH'],
    summary: 'Tier-1 Indian IT service exporters report stable pipeline replenishment in cloud migration and agentic AI pilot deployments for US banking giants.',
  },
  {
    id: 'news-6',
    headline: 'Tata Steel Secures UK Grant of £500M for Port Talbot Green Electric Arc Furnace Transition',
    source: 'Financial Express',
    timeAgo: '4h 05m ago',
    timestamp: '10:55 IST',
    category: 'Corporate',
    impact: 'Medium',
    relatedSymbols: ['TATASTEEL', 'JSWSTEEL'],
    summary: 'The British government subsidy agreement provides long-term decarbonization pathway clarity and curbs recurring cash burns at the European subsidiary.',
  },
];

export const mockMarketContextItems: MarketContextItem[] = [
  {
    id: 'ctx-1',
    title: 'Crude Cooling Benefits Indian Equities',
    impactLevel: 'High',
    affectedSectors: ['Automobiles', 'Aviation', 'Oil & Gas', 'Paints'],
    summary: 'A sub-$72 crude price curbs India’s current account deficit and inflation trajectory, providing RBI room for liquidity easing while expanding gross margins for consumer & paint manufacturers.',
  },
  {
    id: 'ctx-2',
    title: 'Bank Nifty Heavyweights Break 52,000 Range',
    impactLevel: 'High',
    affectedSectors: ['Banking', 'Financial Services'],
    summary: 'HDFC Bank and ICICI Bank institutional accumulation is lifting the headline benchmark index out of a 6-week consolidation channel, triggering short-covering in weekly options.',
  },
  {
    id: 'ctx-3',
    title: 'China Stimulus Package Drives Metal Re-rating',
    impactLevel: 'Medium',
    affectedSectors: ['Metals & Mining'],
    summary: 'PBOC liquidity injection and property support package have energized global commodity prices, benefiting domestic metal producers including Tata Steel and Hindalco.',
  },
];
